WIP push requirement to php 7.2
shopwareLabs/psh pull request #106
Opened 2020-10-13 12:13 UTC by JanPietrzyk

2020-10-21 11:03 UTC, Crease29 requested changes

2020-10-21 11:03 UTC, Crease29 commented on .php_cs
> +            'syntax' => 'short'
```suggestion
            'syntax' => 'short',
```

2020-10-21 11:03 UTC, Crease29 commented on .php_cs
> +            'single_line' => true
```suggestion
            'single_line' => true,
```

2020-10-21 11:03 UTC, Crease29 commented on .php_cs
> +            'spacing' => 'one'
```suggestion
            'spacing' => 'one',
```

2020-10-21 11:03 UTC, Crease29 commented on .php_cs
> +            'only_untyped' => true
```suggestion
            'only_untyped' => true,
```

2020-10-21 11:03 UTC, Crease29 commented on README.md
> +This will create a release phar in the `build/psh.phar` directory. The project itself requires PHP7.2+.
```suggestion
This will create a release phar in the `build/psh.phar` directory. The project itself requires PHP 7.2+. 
```

2020-10-21 11:03 UTC, Crease29 commented on composer.json
> +        "bin": "echo 'bin not installed'",
What is this needed for?

2020-10-21 11:03 UTC, Crease29 commented on src/ScriptRuntime/Execution/ProcessExecutor.php
>       * ProcessExecutor constructor.
This whole comment can be removed.

2020-10-21 11:03 UTC, Crease29 commented on tests/Unit/Application/ClimateLoggerTest.php
> +        self::assertStringContainsString('Executed Successfully', MockWriter::$content);
```suggestion
        $this->assertStringContainsString('Executed Successfully', MockWriter::$content);
```

Please fix this in the whole project.

2020-10-21 11:03 UTC, Crease29 commented on tests/Unit/Config/XmlConfigFileLoaderTest.php
> +        $this->assertEquals(['FOO' => 'bar'], $config->getConstants());
```suggestion
        self::assertEquals(['FOO' => 'bar'], $config->getConstants());
```

Please fix this in the whole project.

2020-10-21 11:03 UTC, Crease29 commented on tests/Unit/Config/XmlConfigFileLoaderTest.php
>          $this->assertInstanceOf(Config::class, $config);
```suggestion
        self::assertInstanceOf(Config::class, $config);
```

Please fix this in the whole project.

2020-10-21 11:42 UTC, JanPietrzyk commented on tests/Unit/Config/XmlConfigFileLoaderTest.php
>          $this->assertInstanceOf(Config::class, $config);
Already done, is part of a later pr

2020-10-21 11:42 UTC, JanPietrzyk commented on tests/Unit/Config/XmlConfigFileLoaderTest.php
> +        $this->assertEquals(['FOO' => 'bar'], $config->getConstants());
Already done, is part of a later pr

2020-10-21 11:43 UTC, JanPietrzyk commented on tests/Unit/Application/ClimateLoggerTest.php
> +        self::assertStringContainsString('Executed Successfully', MockWriter::$content);
Already done, is part of a later pr

2020-10-21 11:44 UTC, JanPietrzyk commented on src/ScriptRuntime/Execution/ProcessExecutor.php
>       * ProcessExecutor constructor.
I'll commit this on #109

2020-10-21 11:46 UTC, JanPietrzyk commented on composer.json
> +        "bin": "echo 'bin not installed'",
It's part of the `bin-plugin` used to install box,psalm & infection (in #109).

2020-10-21 11:50 UTC, JanPietrzyk commented on .php_cs
> +            'only_untyped' => true
I ran the fixer on the file, commit in #109

2020-10-21 11:50 UTC, JanPietrzyk commented on .php_cs
> +            'spacing' => 'one'
I ran the fixer on the file, commit in #109

2020-10-21 11:50 UTC, JanPietrzyk commented on .php_cs
> +            'single_line' => true
I ran the fixer on the file, commit in #109

2020-10-21 11:50 UTC, JanPietrzyk commented on .php_cs
> +            'syntax' => 'short'
I ran the fixer on the file, commit in #109

2020-10-21 11:52 UTC, JanPietrzyk commented on README.md
> +This will create a release phar in the `build/psh.phar` directory. The project itself requires PHP7.2+.
change is in #109

2020-10-21 12:50 UTC, HoelShare approved these changes

2020-10-22 12:55 UTC, PascalThesing approved these changes

2020-10-24 12:03 UTC, Crease29 approved these changes

2020-10-26 07:40 UTC, closed without merging

2020-10-26 07:40 UTC, JanPietrzyk commented
Will bve merged with #109