Implement descriptions
shopwareLabs/psh pull request #38
Opened 2017-07-14 13:52 UTC by SimonBaeumer

2017-07-16 14:46 UTC, bcremer commented on README.md
> +#DESCRIPTION: My usefull comment.
Typo: usefull -> useful

2017-07-19 08:24 UTC, SimonBaeumer commented on src/Listing/DescriptionReader.php
> +    public function read(array $lines)
self cr, type hint fehlt

2017-07-19 17:38 UTC, JanPietrzyk commented
Regarding the build: You usage of PHPUnits mock builder seems to be the problem. I removed all calls locally and Humbug works again.

2017-07-19 17:42 UTC, JanPietrzyk requested changes
a few last tweaks please

2017-07-19 17:42 UTC, JanPietrzyk commented on src/Listing/ScriptFinder.php
> +                $description = $this->scriptDescriptionReader->read(file($path->getPath() . '/' . $fileName));
why add a description reader that then is not reading the file content?

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +        $finder = new ScriptFinder([], $this->createMock(DescriptionReader::class));
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +            $this->descriptionReaderMock
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +            $this->descriptionReaderMock
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +            $this->descriptionReaderMock
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +            $this->descriptionReaderMock
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +            $this->descriptionReaderMock
the real one could be used as easily here

2017-07-19 17:42 UTC, JanPietrzyk commented on tests/Integration/Listing/ScriptFinderTest.php
> +    public function createEmptyDescriptionReaderMock()
please remove. And if you need a method like that I would prefer a setUp method on top of the test file

2017-07-20 06:04 UTC, SimonBaeumer commented
@JanPietrzyk I removed `createMock` calls and moved the file reading to the `DescriptionReader` class. I didn't have a reason why I implemented the file reading in the `ScriptFinder` ^^

2017-07-20 06:07 UTC, merged