Create description padding based on script name length
shopwareLabs/psh pull request #39
Opened 2017-07-20 07:04 UTC by SimonBaeumer

2017-07-20 07:08 UTC, JanPietrzyk requested changes

2017-07-20 07:08 UTC, JanPietrzyk commented on src/Application/Application.php
> +            $paddingSize = strlen($script->getName()) > $paddingSize ? strlen($script->getName()): $paddingSize;
please use if statements for better readability

2017-07-20 08:11 UTC, JanPietrzyk requested changes

2017-07-20 08:11 UTC, JanPietrzyk commented on src/Application/Application.php
> +    const PADDING_SIZE = 30;
`const MIN_PADDING_SIZE`

2017-07-20 08:11 UTC, JanPietrzyk commented on src/Application/Application.php
> +        $paddingSize = 0;
```php
$maxScriptNameLength = 0;
foreach ($scripts as $script) {
   $scriptNameLength = strlen($script->getName());
   if ($scriptNameLength > $paddingSize) {
      $maxScriptNameLength = $scriptNameLength;
   }
}
return $maxScriptNameLength + self::MIN_PADDING_SIZE;
```

a little more care with naming please

2017-07-20 08:16 UTC, SimonBaeumer commented on src/Application/Application.php
> +        $paddingSize = 0;
done ;)

2017-07-20 08:16 UTC, SimonBaeumer commented on src/Application/Application.php
> +    const PADDING_SIZE = 30;
done ;)

2017-07-21 09:48 UTC, JanPietrzyk approved these changes

2017-07-21 09:48 UTC, merged