Add .env support
shopwareLabs/psh pull request #84
Opened 2019-02-11 15:59 UTC by nlubisch

Issue: #73 

This is an implementation for .env support.

Example file:
```yaml
paths:
  - "dev-ops/common/actions"
const: []
dynamic: []
dotenv:
  - ".env"
environments:
  pipelines:
    paths:
      - "dev-ops/pipelines/actions"
    dotenv:
      - "dev-ops/pipelines/.env"
```
Default-Environment:
Only the .env file is loaded

Pipelines-Environment:
.env is loaded
dev-ops/pipelines/.env overrides variables from the .env file.

2019-02-11 16:24 UTC, nlubisch commented
@teiling88 @JanPietrzyk if this looks good to you, i fix the existing tests.

2019-02-12 08:02 UTC, JanPietrzyk requested changes
Apart from the few minor nit picks extremely good work! I have just a few questions:

* Do you happen to knwo how `vlucas/phpdotenv` compares to `symfony/dotenv`?
* Will env overwrites from the command line work? Something like `> ENV=test ./psh.pahr dump-env`

2019-02-12 08:02 UTC, JanPietrzyk commented on src/ScriptRuntime/ProcessEnvironment.php
> +        if ($extension) {
shouldn't then `PATHINFO_BASENAME` be sufficient?

2019-02-12 08:02 UTC, JanPietrzyk commented on src/ScriptRuntime/ProcessEnvironment.php
> +            $this->dotenvVariables
Not shure if `dotenvVariables` shouldn't be the first, so other psh placeholders can overwrite them....

2019-02-12 08:02 UTC, JanPietrzyk commented on src/Config/Config.php
> +        foreach ($environments as $name => $environmentConfig) {
Not sure this works as expected. Scripts get loaded across all environments so listing is possible. But this is not how placeholders work. They only get loaded from default and optionally the specific environment. See https://github.com/shopwareLabs/psh/blob/135dcf6300351ded294056e06f3d5df9b9cba4d3/src/Config/Config.php#L84

2019-02-12 08:27 UTC, nlubisch commented on src/ScriptRuntime/ProcessEnvironment.php
> +        if ($extension) {
You are right, i fixed it.

2019-02-12 08:27 UTC, nlubisch commented on src/ScriptRuntime/ProcessEnvironment.php
> +            $this->dotenvVariables
I think constants should be the first, then dotenv variables and on top the variables.
Do you agree with this?

2019-02-12 08:27 UTC, nlubisch commented on src/Config/Config.php
> +        foreach ($environments as $name => $environmentConfig) {
So the dotenv files should not inherit?

2019-02-12 08:40 UTC, nlubisch commented
> Do you happen to knwo how `vlucas/phpdotenv` compares to `symfony/dotenv`?
I personally don't know the difference between the packages, they look pretty much the same.
The only intention why i chose vlucas was that it is used in the composer-project.
> Will env overwrites from the command line work? Something like `> ENV=test ./psh.pahr dump-env`
Just tested it and this doesn't work for now.

2019-02-12 08:48 UTC, nlubisch commented
> Will env overwrites from the command line work? Something like `> ENV=test ./psh.pahr dump-env`

I have an idea on how to support environment variables passed by the cli command.
Those environment variables are added to `$_SERVER`.
We can iterate over all environment variables fetched from the .env files, look if any of those envs does exist and override the .env-env with the server-env.

2019-02-12 09:38 UTC, JanPietrzyk commented on src/Config/Config.php
> +        foreach ($environments as $name => $environmentConfig) {
yes, they should but not across psh-environments. AFAIK this code loads all files, regardless of the requested env.

2019-02-12 09:39 UTC, JanPietrzyk commented on src/ScriptRuntime/ProcessEnvironment.php
> +            $this->dotenvVariables
yes

2019-02-12 09:50 UTC, nlubisch commented on src/ScriptRuntime/ProcessEnvironment.php
> +            $this->dotenvVariables
done.

2019-02-12 10:02 UTC, nlubisch commented on src/Config/Config.php
> +        foreach ($environments as $name => $environmentConfig) {
> AFAIK this code loads all files, regardless of the requested env.

I cross checked this and the .env of the default environment and the requested environment are loaded.
I fix the behaviour, that .env only inherit in a environmental scope.

2019-02-12 10:15 UTC, nlubisch commented on src/Config/Config.php
> +        foreach ($environments as $name => $environmentConfig) {
.env's are now inherited in an environmental scope.

2019-02-12 11:53 UTC, nlubisch commented
* Tests are fixed and new ones are added.
* Added a short description for the feature in the README.md

This should be now good to go, @JanPietrzyk :)

2019-02-13 19:51 UTC, JanPietrzyk requested changes
Sorry but same problem here. The tests are IMHO too far away from the actual changed files.

2019-03-01 13:00 UTC, JanPietrzyk approved these changes

2019-03-01 13:01 UTC, merged